name: hello_world
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: Smin Rana <sminrana@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  http: ^0.12.0+2

